### PR TITLE
Fix spelling mistake

### PR DESCRIPTION
**Pull request by nedrichards**

### CODE REVIEW

**Comment by jurf** [comment]
For some reason this change isn’t visible on flathub.org.

**Comment by Barthalion** [comment]
Triggered new build.

**Comment by jurf** [comment]
…still isn’t visible. I guess it’ll be on the next site update?

**Comment by Barthalion** [comment]
The app is wrongly displayed on non-i386 architectures were appdata wasn't updated. Ideally it should get removed for other arches but similarly to app renaming, there is no procedure for this yet (without sshing into server hosting the repo).

**Pull request merged**
